# Generated by Django 5.0.7 on 2024-07-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ammount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_ammount', models.CharField(max_length=10)),
                ('saving_amount', models.CharField(max_length=10)),
                ('ammount_saved', models.CharField(max_length=10)),
                ('result_amount', models.CharField(max_length=10)),
            ],
        ),
    ]
