# Generated by Django 5.0.7 on 2024-07-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crown', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ammount',
            name='ammount_saved',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ammount',
            name='result_amount',
            field=models.CharField(max_length=100),
        ),
    ]
